require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MusiciansController do

  # This should return the minimal set of attributes required to create a valid
  # Musician. As you add validations to Musician, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MusiciansController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all musicians as @musicians" do
      musician = Musician.create! valid_attributes
      get :index, {}, valid_session
      assigns(:musicians).should eq([musician])
    end
  end

  describe "GET show" do
    it "assigns the requested musician as @musician" do
      musician = Musician.create! valid_attributes
      get :show, {:id => musician.to_param}, valid_session
      assigns(:musician).should eq(musician)
    end
  end

  describe "GET new" do
    it "assigns a new musician as @musician" do
      get :new, {}, valid_session
      assigns(:musician).should be_a_new(Musician)
    end
  end

  describe "GET edit" do
    it "assigns the requested musician as @musician" do
      musician = Musician.create! valid_attributes
      get :edit, {:id => musician.to_param}, valid_session
      assigns(:musician).should eq(musician)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Musician" do
        expect {
          post :create, {:musician => valid_attributes}, valid_session
        }.to change(Musician, :count).by(1)
      end

      it "assigns a newly created musician as @musician" do
        post :create, {:musician => valid_attributes}, valid_session
        assigns(:musician).should be_a(Musician)
        assigns(:musician).should be_persisted
      end

      it "redirects to the created musician" do
        post :create, {:musician => valid_attributes}, valid_session
        response.should redirect_to(Musician.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved musician as @musician" do
        # Trigger the behavior that occurs when invalid params are submitted
        Musician.any_instance.stub(:save).and_return(false)
        post :create, {:musician => { "name" => "invalid value" }}, valid_session
        assigns(:musician).should be_a_new(Musician)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Musician.any_instance.stub(:save).and_return(false)
        post :create, {:musician => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested musician" do
        musician = Musician.create! valid_attributes
        # Assuming there are no other musicians in the database, this
        # specifies that the Musician created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Musician.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => musician.to_param, :musician => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested musician as @musician" do
        musician = Musician.create! valid_attributes
        put :update, {:id => musician.to_param, :musician => valid_attributes}, valid_session
        assigns(:musician).should eq(musician)
      end

      it "redirects to the musician" do
        musician = Musician.create! valid_attributes
        put :update, {:id => musician.to_param, :musician => valid_attributes}, valid_session
        response.should redirect_to(musician)
      end
    end

    describe "with invalid params" do
      it "assigns the musician as @musician" do
        musician = Musician.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Musician.any_instance.stub(:save).and_return(false)
        put :update, {:id => musician.to_param, :musician => { "name" => "invalid value" }}, valid_session
        assigns(:musician).should eq(musician)
      end

      it "re-renders the 'edit' template" do
        musician = Musician.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Musician.any_instance.stub(:save).and_return(false)
        put :update, {:id => musician.to_param, :musician => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested musician" do
      musician = Musician.create! valid_attributes
      expect {
        delete :destroy, {:id => musician.to_param}, valid_session
      }.to change(Musician, :count).by(-1)
    end

    it "redirects to the musicians list" do
      musician = Musician.create! valid_attributes
      delete :destroy, {:id => musician.to_param}, valid_session
      response.should redirect_to(musicians_url)
    end
  end

end
